authors:
  thibaud:
    name: Thibaud
    description: Work-study trainee
    avatar: https://secure.gravatar.com/avatar/fe6a1dc8c89c61075331db5ec5936daeba623859b979cb15281845129ab43540?s=1600&d=identicon
