# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

stages:
  - test
  - deploy 

image: python:3.10

before_script:
  - apt update -yq 
  - apt -yq install pandoc
  - pip install -r requirements.txt

test:
  stage: test
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'

pages:
  stage: deploy
  script:
    - mkdocs build --strict --verbose --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
