# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

stages:
  - test
  - deploy 

image: python:3.13.0a3-bookworm

before_script:
  - apt update -yq 
  - apt -yq install pandoc
  - pip install -r requirements.txt

test:
  stage: test
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - mkdocs build --strict --verbose
  artifacts:
    paths:
    - public
  only:
  - master
