site_name: Comfor Documentation
site_author: Eduardo Guzman
site_dir: public
site_url: https://comfor.gitlab.io/comfor-doc
repo_url: https://gitlab.com/comfor/comfor-doc
repo_name: comfor/comfor
copyright: Copyright &copy; 2021 - 2025 Eduardo Guzman

docs_dir: docs

nav:
  - "Home":
      - "Welcome": index.md
  - "Getting Started":
      - "Downloads": overview/download.md
      - "Quick Start": overview/quick_starter_guide.md
      - 'Tutorial': overview/tutorial.md
  - "Docs":
      - "Overview": docs/overview.md
      - "Preprocessing": docs/preprocessing.md
      - "Running": docs/analysis.md
      - "Postprocessing": docs/postprocessing.md
      - "Materials": docs/materials.md
      - "Elements": docs/elements.md
      - "Theory":
        - "Overview": docs/theory/theory_overview.md
        - "Continuum Mechanics": docs/theory/continuum_mechanics.md
        - "Composite Materials": docs/theory/materials/composite_materials.md
        - "Materials overview": docs/theory/materials/materials_overview.md
        - "Solvers": docs/theory/solvers/solvers_overview.md
  - "Developers":
      - "Git": developers/git.md
      - "API": developers/api.md
      - "License": developers/license.md
      - "Code of conduct": developers/code_of_conduct.md
  - "Work with us":
      - "Industry": collaborate/industry.md
      - "Academy": collaborate/academy.md
  - "News":
      - "Publications": news/news_publications.md
  - "FAQ":
      - "FAQ": faq/faq.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/img/logo-icon-innovamics.png
  favicon: assets/img/apple-touch-icon-72x72.png
  analytics:
    gtag: "G-7CEE34RD0F"
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)" # Automatic gestion of user's preferences
      scheme: default # Light theme
      toggle: # Theme changing button
        icon: material/toggle-switch # Theme changing button style
        name: Dark
      primary: black
      #primary: custom
      #accent: custom
      #default: custom
      #typeset: custom
    - media: "(prefers-color-scheme: dark)" # Automatic gestion of user's preferences
      scheme: slate # Dark theme
      toggle: # Theme changing button
        icon: material/toggle-switch-off-outline # Theme changing button style
        name: Light
      primary: black
      #primary: custom
      #accent: custom
      #default: custom
      #typeset: custom
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - admonition #"attention", "caution", "danger", "error", "hint", "important", "note", "tip", "warning", "admonition"
  - attr_list
  - def_list
  - footnotes
  - fenced_code
  - md_in_html # An extension that parses Markdown inside of HTML tags.
  - pymdownx.arithmatex: # LaTeX syntax
      generic: true
  - pymdownx.emoji: # :smile: :heart: :thumbsup:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight: # Code highlighting
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # `==highlighted text==`
  - pymdownx.snippets # `{{snippet_name}}`
  - pymdownx.superfences # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - pymdownx.tasklist # - [X] item
  - pymdownx.tabbed: # === "Tab 1"
      alternate_style: true
  - pymdownx.blocks.caption
  - pymdownx.keys
  - tables
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"

plugins:
  - search
  - ignore_bibtex # Custom plugin to ignore @ outside [@]
  - bibtex:
      bib_file: "docs/Bibliography.bib"
      csl_file: "docs/assets/csl/nature.csl"
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: 🇬🇧 English
          build: true
        - locale: fr
          name: 🇫🇷 Français
          build: true
          nav_translations:
            Home: Accueil
            Welcome: Bienvenue
            Getting Started: Bien démarrer
            Downloads: Téléchargements
            Quick Start: Démarrage rapide
            Tutorial: Tutoriel
            Docs: Manuel
            Overview: Généralités
            Preprocessing: Pré-traitement
            Running: Exécution
            Postprocessing: Post-traitement
            Materials: Matériaux
            Elements: Eléments
            Theory: Théorie
            Continuum Mechanics: Mécanique des milieux continus
            Composite Materials: Matériaux composites
            Materials overview: Matériaux
            Solvers: Solveurs
            Developers: Développeurs
            License: Licence
            Code of conduct: Code de conduite
            Work with us: Travaillez avec nous
            Industry: Entreprise
            Academy: Enseignement
            News: Actualités
          admonition_translations:
            attention: Attention
            danger: Danger
            error: Erreur
            hint: Astuce
            important: Important
            note: Note
            tip: Conseil
            warning: Avertissement

extra_javascript:
  - assets/js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/chart.js@3.2.0/dist/chart.min.js
  - assets/js/xy_graphs.js
  # - assets/js/landing_page.js   
  # - assets/js/table_rtd.js
  # - assets/js/background_effects.js 

extra_css:
  # - assets/css/landing_page.css
  - assets/css/faq_admonition.css
  # - assets/css/tabbed.css
  # - assets/css/home_page.css
  # - assets/css/custom_colors.css
  # - assets/css/background.css
  # - assets/css/test.css # figure formatting
