name: ci

on:
  push:
    branches:
      - "**"

permissions:
  contents: write

env:
  EN_CONFIG: config/en/mkdocs.yml
  FR_CONFIG: config/fr/mkdocs.yml
  SITE_URL_EN: "https://innovamics.github.io/comfor-doc/en"
  SITE_URL_FR: "https://innovamics.github.io/comfor-doc/fr"

jobs:
  test:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: sudo apt-get update -yq
      - run: sudo apt-get install -yq pandoc
      - run: pip install -r requirements.txt
      - run: pip install -e ./plugins/ignore_bibtex
      - run: export SITE_URL="https://innovamics.github.io/comfor-doc"
      - run: mkdocs build -f $EN_CONFIG --strict --verbose --site-dir ../../test/en
      - run: mkdocs build -f $FR_CONFIG --strict --verbose --site-dir ../../test/fr
      - run: ls -R test

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: sudo apt-get update -yq
      - run: sudo apt-get install -yq pandoc
      - run: pip install -r requirements.txt
      - run: pip install -e ./plugins/ignore_bibtex
      - run: export SITE_URL="https://innovamics.github.io/comfor-doc"
      - run: mkdocs build -f $EN_CONFIG --strict --verbose --site-dir ../../public/en
      - run: mkdocs build -f $FR_CONFIG --strict --verbose --site-dir ../../public/fr
      - run: cp extra/googlef388943a115bc8cc.html public/en/googlef388943a115bc8cc.html
      - run: cp extra/googlef388943a115bc8cc.html public/fr/googlef388943a115bc8cc.html
      - run: cp extra/robots.txt public/robots.txt
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public